#!/bin/sh

# Copyright (c) 2025 John A Kline
# See the file LICENSE for your full rights.

# For testing, set etc to /tmp/etc
etc="/etc"
#etc="/tmp/etc"

if [ "$etc" = "/tmp/etc" ]; then
  # This is a test run.  Create the /etc directories needed.
  mkdir -p /tmp/etc/init.d 2>/dev/null
  mkdir    /tmp/etc/logrotate.d 2>/dev/null
  mkdir    /tmp/etc/rsyslog.d 2>/dev/null
  mkdir -p /tmp/etc/logwatch/conf/services 2>/dev/null
  mkdir    /tmp/etc/logwatch/conf/logfiles 2>/dev/null
  mkdir -p /tmp/etc/logwatch/scripts/services 2>/dev/null
fi

if [ $# -ne 4 ]; then
  echo "Usage: $0 <src-files> <target-dir> <archive-interval-seconds> <airgradient-dns-name-or-ip>"
  exit 1
fi

src_dir="$1"
target_dir="$2"
archive_interval_seconds="$3"
sensor="$4"

mkdir -p "$target_dir"/archive 2> /dev/null
mkdir -p "$target_dir"/bin/monitor 2> /dev/null
mkdir    "$target_dir"/bin/server 2> /dev/null

if [ -d "/etc/logrotate.d" ]; then
  cp ${src_dir}/etc/logrotate.d/airgradient-proxy ${etc}/logrotate.d/
fi

if [ -d "/etc/logwatch" ]; then
  cp ${src_dir}/etc/logwatch/conf/services/airgradient-proxy.conf ${etc}/logwatch/conf/services/
  cp ${src_dir}/etc/logwatch/conf/logfiles/airgradient-proxy.conf ${etc}/logwatch/conf/logfiles/
  cp ${src_dir}/etc/logwatch/scripts/services/airgradient-proxy ${etc}/logwatch/scripts/services/
fi

if [ -d "/etc/rsyslog.d" ]; then
  cp ${src_dir}/etc/rsyslog.d/airgradient-proxy.conf ${etc}/rsyslog.d/
fi

# cp and fixup /etc/init.d/airgradient-proxy
cat ${src_dir}/etc/init.d/airgradient-proxy | sed "s%/home/airgradientproxy%$target_dir%g" > /${etc}/init.d/airgradient-proxy

# cp bin files
cp ${src_dir}/home/airgradientproxy/bin/server/__init__.py ${target_dir}/bin/server/
cp ${src_dir}/home/airgradientproxy/bin/server/server.py ${target_dir}/bin/server/
cp ${src_dir}/home/airgradientproxy/bin/airgradientproxyd ${target_dir}/bin/
cp ${src_dir}/home/airgradientproxy/bin/monitor/__init__.py ${target_dir}/bin/monitor/
cp ${src_dir}/home/airgradientproxy/bin/monitor/monitor.py ${target_dir}/bin/monitor/

# copy and fix up the wrapper
cat ${src_dir}/home/airgradientproxy/bin/airgradientproxy-wrapper.sh | sed "s%/home/airgradientproxy%$target_dir%g" > ${target_dir}/bin/airgradientproxy-wrapper.sh
chmod +x ${target_dir}/bin/airgradientproxy-wrapper.sh

echo "# AirGradientProxy configuration file" > ${target_dir}/airgradientproxy.conf
echo "debug = 0" >> ${target_dir}/airgradientproxy.conf
echo "log-to-stdout = 0" >> ${target_dir}/airgradientproxy.conf
echo "service-name = airgradient-proxy" >> ${target_dir}/airgradientproxy.conf
echo "hostname = $sensor" >> ${target_dir}/airgradientproxy.conf
echo "port = 80" >> ${target_dir}/airgradientproxy.conf
echo "timeout-secs = 28" >> ${target_dir}/airgradientproxy.conf
echo "long-read-secs = 10" >> ${target_dir}/airgradientproxy.conf
echo "server-port = 8080" >> ${target_dir}/airgradientproxy.conf
echo "poll-freq-secs = 30" >> ${target_dir}/airgradientproxy.conf
echo "poll-freq-offset = 0" >> ${target_dir}/airgradientproxy.conf
echo "archive-interval-secs = $archive_interval_seconds" >> ${target_dir}/airgradientproxy.conf
echo "database-file = ${target_dir}/archive/airgradientproxy.sdb" >> ${target_dir}/airgradientproxy.conf

# If for real...
if [ "$etc" = "/etc" ]; then
    if [ -d "/etc/rsyslog.d" ]; then
        service rsyslog restart
    fi
    if [ -d "/etc/logrotate.d" ]; then
        service logrotate restart
    fi
    chmod +x /etc/init.d/airgradient-proxy
    systemctl enable airgradient-proxy
    /etc/init.d/airgradient-proxy start
fi
